name: Unit Tests

on:
  push:
    branches:
      - Development
  pull_request:
    branches:
      - Development

jobs:
  test:
    runs-on: self-hosted

    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip3 install -r requirements.txt
          python3 setup.py install

      - name: Run unit tests
        run: python3 -m unittest discover -s tests
